name: VitaNetworks
favicon: null
layout_spectrum: 0.7182456436567008
typography_spectrum: 0.8627291356679052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9792437455616891
  lightness: 0.8045080127194524
  saturation: 0.48363575525581837
  rhythmicContrast: 0.021906794514507055
purpose: []
